version: "3.7"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./src/main/resources:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5434:5432'
    volumes:
      - c:/postgres-data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana-enterprise:latest
    user: '0'
    ports:
      - 3000:3000
    volumes:
      -  c:/grafana-data:/var/lib/grafana
