management:
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,prometheus
