spring:
  datasource:
    password: password
    platform: postgres
    url: jdbc:postgresql://localhost:5434/simple
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    health:
      include:
        show-details: always
    web:
      exposure:
        include: "*"
